import type { Pet } from '@repon/types';
import { MascotaInvalidaError } from './consumo.errors';

export type { Pet };

/**
 * design.md Phase 2a (tasks.md 2a.1/2a.2): `nombre`/`especie` must be
 * non-blank. `raza`/`pesoKg` are optional and have no declared invariant in
 * this change (residual — nothing in design.md's "Riesgos residuales"
 * names them either).
 */
function assertMascotaValida(nombre: string, especie: string): void {
  if (nombre.trim() === '') {
    throw new MascotaInvalidaError('nombre no puede estar vacío.');
  }
  if (especie.trim() === '') {
    throw new MascotaInvalidaError('especie no puede estar vacía.');
  }
}

export interface CrearMascotaInput {
  id: string;
  userId: string;
  nombre: string;
  especie: string;
  raza?: string;
  pesoKg?: number;
}

/**
 * Factory (design.md D-H.1). `id` is always generated by the caller via
 * `randomUUID()` and passed in — never a DB default, the repo's uniform
 * precedent (`cargarProductoCatalogo`, `registrarEmpresa`,
 * `asignarRolAdmin`). `userId` always comes from `actor.profileId` in the
 * use case (D8) — this factory just carries it through, it does not derive
 * it.
 */
export function crear(input: CrearMascotaInput): Pet {
  assertMascotaValida(input.nombre, input.especie);

  return {
    id: input.id,
    userId: input.userId,
    nombre: input.nombre,
    especie: input.especie,
    raza: input.raza,
    pesoKg: input.pesoKg,
  };
}
