import type { UserConsumption } from '@repon/types';
import { ConsumoInvalidoError } from './consumo.errors';

export type { UserConsumption };

/**
 * design.md D-H (`configurarConsumo` DTO invariant, tasks.md 2a.3):
 * `petId` MUST be present if-and-only-if `ownerType === 'pet'`. Never
 * present for `'self'` (no pet to own the item), always present for
 * `'pet'` (nothing else identifies which pet).
 */
function assertPetIdMatchesOwnerType(
  ownerType: UserConsumption['ownerType'],
  petId: string | undefined,
): void {
  if (ownerType === 'pet' && !petId) {
    throw new ConsumoInvalidoError("petId es obligatorio cuando ownerType === 'pet'.");
  }
  if (ownerType === 'self' && petId != null) {
    throw new ConsumoInvalidoError("petId no puede estar presente cuando ownerType === 'self'.");
  }
}

/** design.md Diagram 1, step 2a: `consumoDiario` divides by `dosisPorToma` — a zero or negative dose is meaningless input, never a valid schedule. */
function assertDosisPorTomaValida(dosisPorToma: number): void {
  if (!(dosisPorToma > 0)) {
    throw new ConsumoInvalidoError(`dosisPorToma (${dosisPorToma}) debe ser mayor que 0.`);
  }
}

/**
 * `@repon/types`'s `UserConsumption.horarios` is typed as the non-empty
 * tuple `[string, ...string[]]` — this is what makes that type honest: the
 * raw, not-yet-validated input can still be an empty array (e.g. straight
 * off a DTO), and this is the one place that closes the gap before the
 * value is trusted as a `UserConsumption`.
 */
function assertHorariosNoVacios(horarios: readonly string[]): void {
  if (horarios.length === 0) {
    throw new ConsumoInvalidoError('horarios no puede estar vacío.');
  }
}

export interface CrearUserConsumptionInput {
  id: string;
  userId: string;
  ownerType: UserConsumption['ownerType'];
  petId?: string;
  kind: UserConsumption['kind'];
  nombre: string;
  dosisPorToma: number;
  unidad?: string;
  frecuenciaDias: number;
  horarios: readonly string[];
  stockActual: number;
  autoCrearRefill: boolean;
}

/**
 * Factory (design.md Phase 2a, tasks.md 2a.3/2a.4). `id` is always
 * generated by the caller via `randomUUID()` (D-H.1's precedent); `userId`
 * always comes from `actor.profileId` in the use case (D8) — this factory
 * just carries it through. Enforces the 3 invariants above, in order, and
 * throws `ConsumoInvalidoError` on the first one that fails.
 */
export function crear(input: CrearUserConsumptionInput): UserConsumption {
  assertPetIdMatchesOwnerType(input.ownerType, input.petId);
  assertDosisPorTomaValida(input.dosisPorToma);
  assertHorariosNoVacios(input.horarios);

  return {
    id: input.id,
    userId: input.userId,
    ownerType: input.ownerType,
    petId: input.petId,
    kind: input.kind,
    nombre: input.nombre,
    dosisPorToma: input.dosisPorToma,
    unidad: input.unidad,
    frecuenciaDias: input.frecuenciaDias,
    horarios: input.horarios as [string, ...string[]],
    stockActual: input.stockActual,
    autoCrearRefill: input.autoCrearRefill,
  };
}
